cache func add(int a, int b) int {
    effect {
        print("test");
    }
    return a + b;
}
lazy func two() int {
    return 1;
}

func main(int ben, str franzl) double {
    int number = 2;
    int b = 3;
    str str1 = "dquote string";
    str str2 = 'squote string\'';
    str str3 = str1 + str2 + str1;
    lazy str str4 = "aa";
    double d = 1.2345;
    d = 2.5;
    // this is comment
    int sum = add(a,b);
    add(a,b);
    two();
    safe add(a, b);


    if(b > number && 1 == 1 || a | 1 && b << 2) {
        print("this is statement");
    } elseif (str1) {
        // empty block
    } elseif ("test") {
        print("this is expression condition");
    } else {
        print("this is else");
    }

    for(int i = 0; i < len; i = i + 1) {
        if(i == 3) {
            effect {
                print(i);
            }
        } elseif(i % 2) {
            next;
        } elseif(i == 100) {
            break;
        }
        print(i);
    }

    return -1112.1;
}
